### ISSUE TITLE
您好 作者！这个2HG是2层堆叠吗？我记得FAN那些好像是4层的堆叠的，能解释一下吗？谢谢

### ISSUE THREAD

**Issue by wqz960** [face-alignment-group-of-ahucs/SHN-based-2D-face-alignment#12]
如题 还有虽然看了之前的问题，还是对flip不太懂是什么意思。。。

**Comment by wqz960** [comment]
还有您好 我大致粗略地看了下您在背后列出的那篇论文，那篇论文的scores map的ground true map是怎么得到的 谢谢

**Comment by wuneng** [comment]
flip是预测了2次，将原始图像和flip后的图像输出的heatmap求平均。scores map在关键点周围的小邻域都是1，其他地方都是0.
