### ISSUE TITLE
关于使用flip 图像预测问题

### ISSUE THREAD

**Issue by keyxuliang** [face-alignment-group-of-ahucs/SHN-based-2D-face-alignment#5]
out2 = flip_channels(out2.cpu())
out2 = shuffle_channels_for_horizontal_flipping(out2)
请教一下，这两个步骤怎么理解？
个人理解：
    假设原本是1-68个输出通道依次对应的是1-68个点，如果是flip图像进行预测，那么只需要按照flip的对应关系，然后把对应通道的顺序给交换一下就行。为什么还需要flip_channels将每个输出通道的heatmap进行镜像呢？

**Comment by wuneng** [comment]
因为flip会改变关键点的顺序。例如，在flip之后，左眼周围的关键点会变成右眼周围的关键点，这样会导致关键点的顺序混乱。在utils文件中有个show_image函数，你可以测试下只翻转图像且不改变关键点顺序的情况。

**Comment by wuneng** [comment]
使用flip_channels得到的heatmap会与原始图像得到的heatmap相加，然后得到坐标。可以参考https://github.com/princeton-vl/pose-hg-train/blob/2fef6915fbd836a5d218a5d2f0c87c463532f1a6/src/train.lua#L59
