### ISSUE TITLE
我使用您的方法 test的时候Test Inter-pupil Normalisation为0.07这是为什么呀

### ISSUE THREAD

**Issue by silvercherry** [face-alignment-group-of-ahucs/SHN-based-2D-face-alignment#8]

**Comment by wuneng** [comment]
测试的哪个数据集，多少张图片呢？

**Comment by silvercherry** [comment]
> 测试的哪个数据集，多少张图片呢？

就是用的300w-lp那个数据集 测试了35张图片

**Comment by wuneng** [comment]
测试数据集搞错了，测试数据集是helen/testset lfpw/testset 和ibug，总共689张图片。

**Comment by silvercherry** [comment]
> 测试数据集搞错了，测试数据集是helen/testset lfpw/testset 和ibug，总共689张图片。

您好 我是使用的python3 main.py --phase test 这个命令 路径设置也和您的一样
Total params: 4.56M
Start testing...
Elapsed [0:00:11], Iteration [10/35], test_loss: 0.00084, test_rmse: 0.08065
Elapsed [0:00:18], Iteration [20/35], test_loss: 0.00074, test_rmse: 0.07032
Elapsed [0:00:23], Iteration [30/35], test_loss: 0.00074, test_rmse: 0.06712
Test Inter-pupil Normalisation: 0.07346566401855557
Test Inter-pupil Normalisation Best: 0.07346566401855557
Save best checkpoint into checkpoint/models...
但是最后就是这样显示了
