### ISSUE TITLE
测试的一个问题

### ISSUE THREAD

**Issue by silvercherry** [face-alignment-group-of-ahucs/SHN-based-2D-face-alignment#9]
您好 我是使用的python3 main.py --phase test 这个命令 路径设置也和您的一样
Total params: 4.56M
Start testing...
Elapsed [0:00:11], Iteration [10/35], test_loss: 0.00084, test_rmse: 0.08065
Elapsed [0:00:18], Iteration [20/35], test_loss: 0.00074, test_rmse: 0.07032
Elapsed [0:00:23], Iteration [30/35], test_loss: 0.00074, test_rmse: 0.06712
Test Inter-pupil Normalisation: 0.07346566401855557
Test Inter-pupil Normalisation Best: 0.07346566401855557
Save best checkpoint into checkpoint/models...
但是最后就是这样显示了

**Comment by wuneng** [comment]
是要看图片的效果吗？

**Comment by silvercherry** [comment]
> 是要看图片的效果吗？
嗯嗯 一方面想看一下图片效果 
主要的问题是这个Inter-pupil Normalisation的意义是什么 这个数值和您的结果怎么样
新手刚刚入门 是在麻烦大佬了

**Comment by wuneng** [comment]
1）等我今天不忙的时候，我会添加一个测试的demo，可视化对齐效果。不过现在我没有训练好的模型，麻烦你把你训好的模型发到6553947@qq.com。
2）Inter-pupil Normalisation是归一化因子，用于衡量预测关键点与标注关键点的差异。
3）我不知道你用哪个数据集测试的，所以我也不能确定是否正常。

**Comment by silvercherry** [comment]
> 1）等我今天不忙的时候，我会添加一个测试的demo，可视化对齐效果。不过现在我没有训练好的模型，麻烦你把你训好的模型发到[6553947@qq.com](mailto:6553947@qq.com)。
> 2）Inter-pupil Normalisation是归一化因子，用于衡量预测关键点与标注关键点的差异。
> 3）我不知道你用哪个数据集测试的，所以我也不能确定是否正常。

谢谢您的回复 我用的测试集就是您代码中的lfpw以及helen的test
我稍后把训好的模型发给你 
best wishes

**Comment by wuneng** [comment]
你好，我测试了你训练好的模型。感觉效果很差，我不知道是不是你训练的问题。这个代码是我很早之前写的了，我以前测过训练是正常的。另外，我已经增加demo，已经可以可视化对齐效果。

**Comment by silvercherry** [comment]
> 你好，我测试了你训练好的模型。感觉效果很差，我不知道是不是你训练的问题。这个代码是我很早之前写的了，我以前测过训练是正常的。另外，我已经增加demo，已经可以可视化对齐效果。

谢谢您，您能不能分享一下您当时的训练集 我是下载了您代码中的那几个集，代码没有进行修改就直接进行了训练，最后的结果就感觉很差，不知道是什么原因。
